name: e2e_test
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bazel_worker:
    path: ../

dev_dependencies:
  cli_util: ^0.3.0
  dart_flutter_team_lints: ^0.1.0
  path: ^1.8.0
  test: ^1.16.0
