name: e2e_test
dependencies:
  bazel_worker:
    path: ../
dev_dependencies:
  cli_util: ^0.3.0-nullsafety
  path: ^1.8.0-nullsafety
  test: ^1.16.0-nullsafety
environment:
  sdk: '>=2.12.0-0 <3.0.0'
