language: dart

script: ./tool/travis.sh

dart:
  - dev

# Speed up builds by using containerization. Disable this if you need to use
# sudo in your scripts.
sudo: false

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.pub-cache
