include: package:pedantic/analysis_options.yaml

analyzer:

linter:
  rules:
    - always_declare_return_types
    # - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    # - avoid_return_types_on_setters
    - camel_case_types
    # - constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - library_names
    - library_prefixes
    # - non_constant_identifier_names
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    # - type_annotate_public_apis
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
