name: bazel_worker
version: 0.1.8
description: Tools for creating a bazel persistent worker.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/bazel_worker

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
  async: ">1.9.0 <3.0.0"
  protobuf: ">=0.5.0 <0.7.0"

dev_dependencies:
  test: ^0.12.0
