name: bazel_worker
version: 0.1.23+1

description: Tools for creating a bazel persistent worker.
homepage: https://github.com/dart-lang/bazel_worker

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  async: '>1.9.0 <3.0.0'
  pedantic: ^1.8.0
  protobuf: '>=0.14.4 <2.0.0'

dev_dependencies:
  test: ^1.2.0
