name: bazel_worker
version: 1.0.3-dev
description: >-
  Protocol and utilities to implement or invoke persistent bazel workers.
repository: https://github.com/dart-lang/bazel_worker

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.5.0
  protobuf: ^2.0.0

dev_dependencies:
  dart_flutter_team_lints: ^0.1.0
  test: ^1.16.0
